// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test 1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test 1', async function() {
    await driver.get("https://testpages.eviltester.com/styled/apps/notes/simplenotes.html")
    await driver.findElement(By.id("note-title-input")).click()
    await driver.findElement(By.id("note-title-input")).sendKeys("Test Note 1")
    await driver.findElement(By.id("note-details-input")).click()
    await driver.findElement(By.id("note-details-input")).sendKeys("This is a test note.")
    await driver.findElement(By.id("add-note")).click()
    assert(await driver.findElement(By.css(".title-note-in-list")).getText() == "Test Note 1")
    await driver.findElement(By.css(".edit-note-in-list")).click()
    await driver.findElement(By.css(".title-input")).click()
    await driver.findElement(By.id("note-title-input")).sendKeys("Updated Note")
    await driver.findElement(By.id("note-details-input")).click()
    await driver.findElement(By.id("note-details-input")).click()
    {
      const element = await driver.findElement(By.id("note-details-input"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("note-details-input")).sendKeys("This note has been updated.")
    await driver.findElement(By.id("update-note")).click()
    assert(await driver.findElement(By.css(".title-note-in-list")).getText() == "Updated Note")
    await driver.findElement(By.id("manage-storage-link")).click()
    assert(await driver.findElement(By.css("summary")).getText() == "This note has been updated.")
    await driver.findElement(By.css(".delete-note-in-list")).click()
    assert(await driver.switchTo().alert().getText() == "Are you sure you want to delete Note?\n\nUpdated Note\n1733585775609-8169369885697484")
    await driver.switchTo().alert().accept()
    assert(await driver.findElement(By.id("note-status-details")).getText() == "Deleted Note: 1733585775609-8169369885697484")
    await driver.findElement(By.id("edit-storage-link")).click()
    await driver.findElement(By.id("note-title-input")).click()
    await driver.findElement(By.id("note-title-input")).sendKeys("Test Note 1")
    await driver.findElement(By.id("note-details-input")).click()
    await driver.findElement(By.id("note-details-input")).sendKeys("This is a test note.")
    await driver.findElement(By.id("add-note")).click()
    {
      const element = await driver.findElement(By.id("add-note"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("note-title-input")).click()
    await driver.findElement(By.id("note-title-input")).sendKeys("Test Note 2")
    await driver.findElement(By.id("note-details-input")).click()
    await driver.findElement(By.id("note-details-input")).sendKeys("This is a second test note.")
    await driver.findElement(By.id("add-note")).click()
    await driver.findElement(By.id("note-title-input")).click()
    await driver.findElement(By.id("note-title-input")).sendKeys("Test note 3")
    await driver.findElement(By.id("note-details-input")).click()
    await driver.findElement(By.id("note-details-input")).sendKeys("This is a third test note.")
    await driver.findElement(By.id("add-note")).click()
    await driver.findElement(By.id("load-notes")).click()
    await driver.findElement(By.id("session-storage-link")).click()
    await driver.findElement(By.id("local-storage-link")).click()
    await driver.findElement(By.id("manage-storage-link")).click()
    await driver.findElement(By.id("clear-notes")).click()
    assert(await driver.switchTo().alert().getText() == "Are you sure you want to delete all notes")
    await driver.switchTo().alert().accept()
  })
})
